### ISSUE TITLE
NaN filling as a part of the sklearn pipeline?

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#101]
EDIT: @epa095 claims that this might not be possible or at least nice. Because - at training time, you have a full frame and you use _context_ (for example previous value to fill). But on prediction, you should not need any contextual information, except things set "statically" from the training (like an average value, max value etc). SO - do not implement this thing before a thorough discussion.

Currently, the different tag series are resampled AND NaN filled before the sklearn pipeline. 

I think perhaps that "everything" would work if we skipped the NaN filling in the dataset classes, and rather expect it to be done as a part of the pipeline. We will still do the resampling and "inner join" of the individual tag series - but leave the NaNs.

The motivation is to leave decisions on how to fill to the "user".

**Comment by epa095** [comment]
Should we close this @flikka ? Seems like that to me.
