### ISSUE TITLE
Change feedforward_symetric/feedforward_model to not have as many optional parameters

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#130]
Today it has the following optional parameters
```
 enc_dim: List[int] = None,
 dec_dim: List[int] = None,
 enc_func: List[str] = None,
 dec_func: List[str] = None,
```
But when #128 is merged we will have builders which are more natural to use when you don't know the dimensions you want, so then it is maybe better to make these parameters non-optional. Will maybe break some stuff, but who cares. 

Relates to #127

**Comment by epa095** [comment]
This should be discussed a tiny bit before starting it. The error validation is a no-brainer, so that is good, but maybe not the non-optionality. I no longer see any strong reasons for making them compolsory.

**Comment by ryanjdillon** [comment]
I can pick up all of these API dealies. Maybe we could have said discussion i dag and roll them all up into one issue.
