### ISSUE TITLE
Should pytest go to install_requires?

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#151]
I tried running `python setup.py test` on travis, and xdist failes. Moving `"pytest==4.0.0",` from `test_requirements` to `install_requires` fixed it, and indeed all environments where we have been running xdist have pytest installed anyway, so maybe it is actually a dependency? Try to create a fresh conda environment and see if you can reproduce the error by running `python setup.py test`, and if it is fixed by installing pytest.

**Comment by milesgranger** [comment]
I just tried this with a new virtual env. Aside from `setup.py` failing to find tensorflow 2.0, of which I suppose is mildly expected as one needs a pretty new pip to also find it...anyway it worked ok.
