### ISSUE TITLE
Discussion: Move argo workflow & generator into components

### ISSUE THREAD

**Issue by milesgranger** [equinor/gordo#181]
Relates to making us useful for open source.

The workflow generator can live in components and require users, ie. gordo-infrastructure, to define a definitions template of sorts which the workflow generator template extends, and uses the defined `models`, `datasets` etc. etc. to generate the workflow. 

This way we can also move the config elements and associated elements into components and enable us to create endpoints which allow for validating config files or...?? :door: :open_hands: :rocket:

**Comment by flikka** [comment]
#534 will finally put and end to this discussion!
