### ISSUE TITLE
Add "anomaly" concept in gordo?

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#195]
This must be discussed, but there appears to be work going on wrt providing "anomaly" signals that transcends the "reconstruction error" and sensor errors. This will probably ongoing development for a long time, looking at trends/weak signals, patterns etc - but we should probably introduce the concept into gordo soon. 

For example as "extra" data series that are supplied as a part of the output/results, could be several "anomaly" series in many variants and levels - for the whole machine and for sensors.

**Comment by epa095** [comment]
This seems to be what miles is doing in #368 with `DiffBasedAnomalyDetector` ?

**Comment by milesgranger** [comment]
@flikka can this be closed?

Seems any additional variations of anomalies have a clear way forward now, following the pattern of `DiffBasedAnomalyDetector`. While #449 is something that is related but not complete?

**Comment by flikka** [comment]
I agree! This is fine done, and the “flagging” stuff is in #449

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
