### ISSUE TITLE
Improve batching in prediction client for LSTM 

### ISSUE THREAD

**Issue by Natalie-Caruana** [equinor/gordo#236]
We have (at least) the following issues:
* If the batch size is too small (smaller than lookback window (approx, this varies between autoencoder and forecast) you get too little data in each batch to do the LSTM.
* The last batch might be too small, even if the previous are big enough (the remainder of the data)
* Between all batches we will loose predictions, since the LSTM need the lookback window to "get started", and for each batch, we get a new start.

One approach to solving it could be that the models provide a "batch overlap" number (which is currently the lookback window - 1, or lookback window) that the client can use to make overlaps between the batches, to make sure all data points possible gets a prediction.

**Comment by milesgranger** [comment]
Closed by #445 and #472
