### ISSUE TITLE
Try intel-tensorflow 

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#245]
There is a intel-tensorflow [on pypi](https://pypi.org/project/intel-tensorflow) and supposedly it can give [quite a speedup](https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture).
Maybe we should try to build our docker images with it, and see it things are faster on the azure world. According to [tensorflow](https://www.tensorflow.org/guide/performance/overview#tensorflow_with_intel%C2%AE_mkl_dnn):
> In addition to providing significant performance improvements for training CNN based models, compiling with the MKL creates a binary that is optimized for AVX and AVX2. The result is a single binary that is optimized and compatible with most modern (post-2011) processors.

Sounds OK. But we should maybe have some benchmark?

**Comment by milesgranger** [comment]
After #319 we decided not to go forward with this. Re-open if I'm mistaken.
