### ISSUE TITLE
Implement filter_buffer

### ISSUE THREAD

**Issue by SveinErikStokka** [equinor/gordo#270]
Aim:
Extend the functionality of "row_filter" to filter "n" samples that do not represent normal running condition. 

Description:
The "row_filter" filters the data that not match a certain condition. Once this condition is met again, the "filter_buffer" filters the next "n" number of samples.

Proposed placeholder in config file:

In bold, you can find the suggested placeholder for the "filter_buffer", added as a parameter in the dataset block:

- name: cooling
    dataset:
      tags:
      - GRA-SE  -23-1290.PV
      - GRA-TE  -23-0735A.PV
      - GRA-TE  -23-0735B.PV
      - GRA-TE  -23-0735C.PV
      - GRA-TE  -23-0735D.PV
      - GRA-TE  -23-0737A.PV
      - GRA-TE  -23-0737B.PV
      - GRA-TE  -23-0737C.PV
      - GRA-TE  -23-0737D.PV
      - GRA-NRA -23-0413.PV
      train_start_date: 2015-07-02T00:00:00+01:00
      train_end_date: 2015-09-15T00:00:00+01:00
      row_filter="`GRA-NRA -23-0413.PV` > 8500"
      **filter_buffer=12**
    model:
      sklearn.pipeline.Pipeline:
        steps:
        - sklearn.pipeline.FeatureUnion:
          - sklearn.preprocessing.data.MinMaxScaler
        - gordo_components.model.models.KerasAutoEncoder:
            kind: feedforward_hourglass

**Comment by flikka** [comment]
NOTE: We have discussed this some more, and the most "pressing" reason to consider this is that it might be needed (but not necessarily) by the "make anomaly flag" feature.
