### ISSUE TITLE
Drop column(s) in pipeline

### ISSUE THREAD

**Issue by SveinErikStokka** [equinor/gordo#271]
Aim:
Drop column(s) that should not be used for training and testing the model.

Description:
Sensor(s) loded in the dataset block, used for filtering etc., and that is not specified as relevant sensor for training(by SME), should be dropped. This will be a part of the preprocessing in the pipeline, in the model block.

Example of jaml file with DropColumns(in bold):

Here, the 'GRA-NRA -23-0413.PV' sensor is used for filtering, but it is not specified as a relevant sensor for training the model.

name: cooling
    dataset:
      tags:
        - GRA-SE -23-1290.PV
        - GRA-TE -23-0735A.PV
        - GRA-TE -23-0735B.PV
        - GRA-TE -23-0735C.PV
        - GRA-TE -23-0735D.PV
        - GRA-TE -23-0737A.PV
        - GRA-TE -23-0737B.PV
        - GRA-TE -23-0737C.PV
        - GRA-TE -23-0737D.PV
        - GRA-NRA -23-0413.PV
      train_start_date: 2015-07-02T00:00:00+01:00
      train_end_date: 2015-09-15T00:00:00+01:00
      row_filter="GRA-NRA -23-0413.PV > 8500"
    model:
      sklearn.pipeline.Pipeline:
        steps:
          **- gordo_components.dataset.DropColumns:
              tags: GRA-NRA -23-0413.PV**
          - sklearn.preprocessing.data.MinMaxScaler
          - gordo_components.model.models.KerasAutoEncoder:
              kind: feedforward_hourglass

**Comment by milesgranger** [comment]
This is actually supported by sklearn: https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

```python
>>> X
   col1  col2
0     0     0
1     1     2
2     2     4
3     3     6
4     4     8
>>> pipe = Pipeline([
...     ('ct', ColumnTransformer(transformers=[('dropper', 'drop', 'col2')],  remainder='passthrough')), 
...     ('pca', PCA())
... ])
>>> pipe.fit_transform(X)
array([[ 2.],
       [ 1.],
       [-0.],
       [-1.],
       [-2.]])

```

**Comment by epa095** [comment]
Note that the `sklearn` solution by @milesgranger is useful when #368  is merged.
