### ISSUE TITLE
Dataset: Add ability to have several resample methods

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#278]
Today we only resample with mean. I propose that we can not only choose another method (e.g. max), but that we support getting a *list* of resample-methods, and then we use all of them (so returning `n*|tag_list|` columns for `n` methods). That way one can set `resample_methods = ["mean","max","min"]` and one would get out `3*|tag_list|` columns with the different resample methods applied.

**Comment by flikka** [comment]
I like the idea, but suspect that the PR is WIP.
