### ISSUE TITLE
Align feedforward_autoencoder and lstm_autoencoder scripts

### ISSUE THREAD

**Issue by Natalie-Caruana** [equinor/gordo#283]
Currently there are some differences between the scripts feedforward_autoencoder.py and lstm_autoencoder.py
1. for example the feedforward_autoencoder uses enc_dim as argument for the encoding layers whereas the lstm_autoencoder
uses encoding_dim (similarly for dec_dim, enc_func, dec_func).  
Need to harmonize such argument names.
2. the encoding dimension is a list in feedforward_autoencoder.py and a tuple in lstm_autoencoder.py (same for dec_dim, enc_func, dec_func).  Need to change the lists to tuples.

It would also be useful
1. to raise an error if the encoding_dim is a string (same for dec_dim, enc_func, dec_func) instead of tuple.
2. to add some logging to warn the user of inputting the incorrect argument names (as these will be dumped in **kwargs and ignored, hence the default values will be used instead)

Check that example notebooks are aligned with the changes.

**Comment by ryanjdillon** [comment]
>1. to raise an error if the encoding_dim is a string (same for dec_dim, enc_func, dec_func) instead of tuple.

This seems like it could be tied into [Erik's comment](https://github.com/equinor/gordo-components/issues/130#issuecomment-467005835) over on #130, maybe in its own issue

**Comment by ryanjdillon** [comment]
We will check that passing an unknown keras optimizer kwarg in `optimizer_kwargs` in the kwargs won't break anything. The goal being to start passing `decay` in `optimizer_kwargs`, and perhaps other algo args not in the gordo API.

[Most, but not all](https://github.com/keras-team/keras/blob/master/keras/optimizers.py), optimizers accept `decay` as an arg.

**Comment by ryanjdillon** [comment]
> 1. to raise an error if the encoding_dim is a string (same for dec_dim, enc_func, dec_func) instead of tuple.
> 2. to add some logging to warn the user of inputting the incorrect argument names (as these will be dumped in **kwargs and ignored, hence the default values will be used instead)

I didn't close this before, because I did not implement these things. Is this still something we would like to do @Natalie-Caruana?
