### ISSUE TITLE
Dataprovider: Support retry on read-failure(?)

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#328]
We sometimes get the dreaded `azure.datalake.store.exceptions.DatalakeIncompleteTransferException: Repeated zero byte reads. Possible file corruption`, and then when we try to read again a bit later it works. Should the dataprovider try to read again a few times it self, e.g. up to 5 times before giving up?

**Comment by ryanjdillon** [comment]
Azure appears to already be [retrying 5 times themselves](https://github.com/Azure/azure-data-lake-store-python/blob/d7293c7690870bf730f3001ac64933a4183d9e8d/azure/datalake/store/core.py#L1165-L1170). It seems kinda much if we need 25 attempts to get a successful read. 

Should we perhaps send this their way to see if there is something else that can be addressed?

**Comment by epa095** [comment]
Good catch @ryanjdillon. I agree.
