### ISSUE TITLE
Change our AutoEncoders to take target (Y) that we fit the model to.

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#364]
Today, we don't take in the target - so we try to fit the neural network to the same as the inputs. In the case of pipelines, this could be scaled data, or even feature reduced or added.

This way - it is not obvious what comes out of the .predict() function.

Suggestion is to supply the X (original data into the pipeline) as the target as well - so that the end result is that what you get from the .predict() is the same dimension (number of targets) and same scale as the X you sent in.

This will make the autoencoder more similar to other "predict" type of models, where we have targets that we fit towards. Scoring will be easier, interpreting results will be easier, and doing things like feature selection in the pipeline will actually work.

Another effect is that then we can treat the "anomaly-calculations" the same way for the autoencoder, as for a multi-target regression. It is simply the error between the predicted output and the real output - the only difference being that the autoencoder has the same input as the target, but the regression will typically split the tags into some used as X to calculate some others, that will become Y.

This task is not small, it affects a lot of things, but it seems very much like the right thing to do.

**Comment by epa095** [comment]
I agree on this completely! Maybe we should have somewhere, either in gordo-infrastructure, or in the model builder, that if the dataset dont have a `target_tag_list` set then it gets set to the value of `tag_list`? That way we are backwards-compatible.
