### ISSUE TITLE
Scaling inside a FeatureUnion breaks the inverse_transform

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#371]
There _seems_ to be a bug somewhere, @jieliu218 showed me an output from a call, both on the /prediction and the /anomaly/prediction endpoint (for the get-versions) where the inverse-transform-model-output seemed to lack the "inverse-tranform"

After some more testing, I can see that the problematic project has the minmax scaler inside a FeatureUnion. I guess this is the reason - that the inverse_transform is done on the FeatureUnion (or not at all, if it doesnt have inversed transform?).

**Comment by milesgranger** [comment]
I don't think feature union has an inverse transform.
