### ISSUE TITLE
Install pandas recomended libs

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#385]
Pandas recommends installing `numexpr` and  `bottleneck` to speed up stuff. We have `numexpr` in our requirements.in (even though it is not really a requirement for us), but not `bottleneck`. Maybe just add it, and run tests and see if stuff works?

https://pandas.pydata.org/pandas-docs/version/0.25/install.html#recommended-dependencies

**Comment by EinarJohnsen** [comment]
Bottleneck requires ```python3-dev``` installed. This would require to use a different docker image with python-dev, and a dependency to keep track of in the docker image. Benchmark tests should be performed before changing this.
