### ISSUE TITLE
Use yaml/json instead of `literal_eval`

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#390]
In `gordo-components/gordo_components/cli/cli.py` it seems a bit random what is parsed as json and what is parsed with `literal_eval`. Maybe just use yaml for all (since json is a subset of yaml, yaml should be the most accepting one)? What U think @milesgranger ?

**Comment by milesgranger** [comment]
Maybe that'll work just as good, we used `literal_eval` because `json` fails if the value is passed with single quotes, and remained safe alternative to `eval`.
