### ISSUE TITLE
Bump base docker python images to latest 3.6 release

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#396]
We are using 3.6.8, but 3.6.9 is the latest.

**Comment by milesgranger** [comment]
Should we do simply, 3.6 then?
![image](https://user-images.githubusercontent.com/13764397/62780323-bc268a00-bab5-11e9-81a1-6177142dca7e.png)

**Comment by epa095** [comment]
I definitely vote *against* using `3.6`, since I :heart:  pinned versions.

**Comment by milesgranger** [comment]
W.E.T.

They are tested in our pipeline before being available for use in _our_ releases. Meaning if we make a release @0.25.0 and Python was 3.6.7 then that's what gordo_components:client:0.25.0 will be. 

Additionally, we test on python 3.6 not patch versions of Python.

Do I misunderstand?

**Comment by epa095** [comment]
But with a floating image like that we get that if we rebuild an old release (by e.g. doing re-build in travis), we can get a different docker-image than we had before.
