### ISSUE TITLE
Exponential retries in client

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#411]
The client supports retrying requests for predictions, but it does the requests right after another. Maybe better to do exponential backof? I found the python library [tenacity](https://tenacity.readthedocs.io/en/latest/) which is supposed to make retries easy and nice, and it includes exponential retries as one method. Maybe use it instead of our own little loop? And then maybe also do #343 at the same time?

**Comment by milesgranger** [comment]
Is this a problem though? Seems like most errors we get with the client are outside of this scope or at least wouldn't be solved with such a lib.

Additionally, it seems a touch buggy with `async` https://github.com/jd/tenacity/issues/181#issue-469246236

**Comment by epa095** [comment]
When we add retries to influx (#343) exponential retries would definitely be a good idea to let the influx settle down again. Using the library is not important though, creating our own exponential-retry logic should be a few lines.
