### ISSUE TITLE
Create a dev-requirements.txt

### ISSUE THREAD

**Issue by milesgranger** [equinor/gordo#412]
Problem
----------
We have a lot of a unnecessary install requirements in our project.

Such as:
https://github.com/equinor/gordo-components/blob/522feaec8c1d50bc62f4b79e6735d62ac3e5ea4b/requirements.in#L22

This ends up having the end user install these packages whilst installing gordo-components.

Solution?
-----------
Create a `dev_requirements.txt` and move these unneeded requirements into that, which would then be installed in Travis/local dev but would not end up requiring the end user to install these.

**Comment by epa095** [comment]
Good idea! Are all the exampled build dependencies which are needed to build the package/documentation?

**Comment by Patil2099** [comment]
@milesgranger Can I work on this?
