### ISSUE TITLE
Push docker images to dockerhub

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#424]
We are open source now, so it makes sense to push all the docker-images to dockerhub. It will also facilitate the opening of gordo-infrastructure, since we can then have the dockerhub-versions of components as the defaults.

**Comment by milesgranger** [comment]
What repo shall we have, as there seems to be no `equinor` there? `gordo`

**Comment by epa095** [comment]
> What repo shall we have, as there seems to be no `equinor` there? `gordo`

Il try to figure that out.

**Comment by milesgranger** [comment]
Closed by #442 I believe.
