### ISSUE TITLE
Add asset-to-path logic for all IOC assets

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#459]
I _think_ this is the list. Look in the datalake for each of them, and add the needed goodness.

1125 - Kvitebjørn
1130 - Troll A
1138 - Valemon
1163 - Gudrun
1180 - Norne
1190 - Åsgard A
1191 - Åsgard B
1218 - Gina Krog
1219 - Aasta Hansteen
1230 - Visund
1755 - Grane
1775 - Troll B
1776 - Troll C

**Comment by EinarJohnsen** [comment]
Some of these are already in our project, the ones I can not find is: ```1219 - Aasta Hansteen``` and ```1230 - Visund```. For Visund there exists a path with metadata but no sensordata, and for Asta Hansteen I can not find anything at all.
