### ISSUE TITLE
Make function that takes "machine" type and params and spits out model definition

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#467]
Today, in the "IOC to Gordo" converter we have hard-coded a couple of models, where the default is a feed-forward autoencoder. We have discussed that the Data Science team looks at the possibility to make general "somewhat better" guesses on the model definition.

**Comment by ryanjdillon** [comment]
I have a rough, perhaps gross, start to this [here](https://github.com/equinor/gordo-analysis/blob/master/gordo_analysis/src/gordo_analysis/analysis.py#L202-L253)

**Comment by ryanjdillon** [comment]
There is an example for Miles's `KerasRawModelRegressor` in the test-project now [here](https://github.com/equinor/gordo-test-project/pull/41), and going to close this now since it somewhat stale.
