### ISSUE TITLE
Add support for Paper "demo" data

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#473]
In the datalake, under /transform/dcoeMdml/paper_1 the "Paper dataset" is added with one file per tag, one file per year. So it should be trivial to add support for that dataset in gordo-components. 

It could be a cool way of demoing the project, also with some supervised learning.

**Comment by epa095** [comment]
This is done now with `dl_base_path` aint it @flikka ?

**Comment by flikka** [comment]
Correct @epa095 - example in https://github.com/equinor/gordo-test-project/pull/29
