### ISSUE TITLE
RFC: Client refactoring for repeated small calls to different models

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#513]
Today the clients downloads all the metadata at init, and filters to whatever machine(s) it is set to use. Then it can only be used for those machines. This is a bit suboptimal if you want to do continuous calls to many (e.g. 9000) different machines, since with todays architecture you would either have to make new clients all the time (resulting in massive metadata-downloads), or you would cache all the 9000 clients. There are probably many ways to solve this, but here are some loose thoughts: 

- Maybe the client should by default download and keep the metadata for all machines at init, so a given client can be used with any machine? Then `predict` needs to take the machine name.
- Maybe the metadata should be handled by a seperate class, which given a project-name, project-version, and machine-name gives the metadata? And this thing can be passed to the client. Then the metadata is not duplicated in all the many client instances? This can be a singleton global object :scream:  ! 

Other thoughts @mrdeveloperdude  @milesgranger  ?

**Comment by mrdeveloperdude** [comment]
The modern name for "singleton global object" is "Context", and the primary
innovation which makes them not a bad practice is that there can coexist
many, and you manage them in such a way that there is only one, or as few
as feasible.

The benefits beyond this is that you can then decide at initialization time
what you want to do, create many or share one etc.

:)

**Comment by flikka** [comment]
@epa095 has more details on this and will rewrite this task (or make a new one and close this)
