### ISSUE TITLE
Support PARQUET files when they arrive for the yearly NCS files

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#550]
The OMNIA plant team will move over to Parquet files for the "yearly" files we use.

The old CSV files will lie around, this should mean that old versions of Gordo will still work. The csv files will not be updated though.

The location is not yet known.

EDIT: We can start testing this a bit, because it is added to the dev datalake. A path that has data is for example: /transform/corporate/Aspen MS - IP21 Grane/sensordata/1755-GRA/GRA-EM  -63-0001ACV.PV/2019/GRA-EM  -63-0001ACV.PV_2019.parquet

Note - the prod path will be /transform/corporate/Aspen MS - IP21 Grane/sensordata/1755-GRA/GRA-EM  -63-0001ACV.PV/GRA-EM  -63-0001ACV.PV_2019.parquet - more or less just like we have now for the csv (but with transform in the start).

**Comment by EinarJohnsen** [comment]
I have code which supports parque files at: https://github.com/EinarJohnsen/gordo-components/tree/test_parque_files.
