### ISSUE TITLE
Try python 3.7

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#559]
This involves:
- Changing all the docker images to be based on python 3.7, and test that stuff works
- Install gordo in an environment with 3.7 and check if things work. 
- Change python version in travis and circleci.

**Comment by ryanjdillon** [comment]
[This](https://github.com/ryanjdillon/gordo-components/blob/b65a54e94b8e912063a57ff6a607e696147c8233/gordo_components/builder/build_model.py#L553-L563) could also be resolved if we're not intending to support <3.7:
```python
553                         # Why not shutil.copytree? Because in python <3.7 it causes
554                         # errors on Azure NFS, see:
555                         # - https://bugs.python.org/issue24564
556                         # - https://stackoverflow.com/questions/51616058/shutil-copystat-fails-inside-docker-on-azure/51635427#51635427
557                         copy_tree(
558                             str(cached_model_location),
559                             str(output_dir),
560                             preserve_mode=0,
561                             preserve_times=0,
562                         )
```
