### ISSUE TITLE
Completely remove any dependency on ambassador

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#565]
Even after moving to istio with #563 we still require ambassador for internal routing. To fix this we mainly need to change the client, so it can take in different base-urls for watchman vs the model-server, so it can contact them directly.

**Comment by milesgranger** [comment]
Not sure I understand this.
Does Istio not allow the same routing features as Ambassador?

**Comment by epa095** [comment]
Currently only from the outside, there is no way to reach the istio gateway from the inside of the cluster in the same way as we today reach ambassador from the inside (or at least, there is no way to reach it without also having to authenticate). But it is possible that we can push for a change there.
