### ISSUE TITLE
Scoring: Enable scaling before scoring

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#579]
We are scoring with the original Y/Ŷ, which in most cases are multivariant timeseries on different scales. For some scoring methods. like `r2`. it does not matter, but for some it does. So maybe we should allow some customization in the `evaluation` config where the user gets to set a scaler which is applied on `Y` and `Ŷ` first?

**Comment by milesgranger** [comment]
This was closed by https://github.com/equinor/gordo-components/pull/599 if I'm not mistaken. Feel free to open if needed.
