### ISSUE TITLE
Support fancy boosting libraries

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#580]
There are many, like CatBoost, Light GBM, and XGBoost. As long as they have a scikit learn wrapper for regression we should be able to use them as long as we add it to the requirements-file. Should we add one and test it out?

**Comment by EinarJohnsen** [comment]
I think this is a good idea, it would show more flexibility and be fun to test out.

**Comment by ryanjdillon** [comment]
Have things working with XGBoost, which required installing the `libgomp1` library on the builder/server images. It took ca.8x longer to build the model. I used the exact implementation of Kristian's RandomForestRegressor w/ featire agglomeration, just swapping the estimator out for `XGBRFRegressor` and the anomalies looked the same w/ a slight change in magnitude. 

Based on this [SO answer](https://datascience.stackexchange.com/a/49616/11122), it looks like LightGBM is much faster. `CatBoost` is said to be slower (but perhaps faster than XGBoost?).

That said, also needs [LightGBM needs glibc](https://github.com/microsoft/LightGBM/tree/master/python-package), which also doesn't appear to come standard issue on `slim-stretch`. [CatBoost](https://catboost.ai/docs/concepts/python-installation.html) appears to not need external libraries outside of `six` and `numpy`.
