### ISSUE TITLE
Update ValidateModel to do some model validation

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#624]
Today, we just check that it is a dict or a string. We could do more! 

@milesgranger probably have good input on this! 

https://github.com/equinor/gordo-components/blob/b65a54e94b8e912063a57ff6a607e696147c8233/gordo_components/workflow/config_elements/validators.py#L80

**Comment by milesgranger** [comment]
Ah, we're really reaping the benefits now! First thought is to just check if `serializer.pipeline_from_defintion` will work on it? :man_shrugging:

**Comment by epa095** [comment]
> Ah, we're really reaping the benefits now! First thought is to just check if `serializer.pipeline_from_defintion` will work on it? man_shrugging

Good first step. Possible next is to try to fit it with random data and see if it crashes
