### ISSUE TITLE
Configfile: Remove per-model server resources

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#665]
Today we support setting resource limit/requests in the configfile for server/builder/client in several ways:

- They can all be set in the globals section, and then they hold for all. 
- The server can (I think) also be set per model, but the client and model-builder can not. 

The latter made sense before when we had one server per model, but not now when we have only one server. So now it should not be possible to set it per model, but only in the globals section. Probably mostly involves removing tests and some special code.

**Comment by ryanjdillon** [comment]
Working on this while I wait for some Aurora response.
