### ISSUE TITLE
docker images: run as non-root user

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#681]
Today we run gordo as the default user inside the docker images, which I think is root. This is bad practice, instead we should add a non-root user (e.g. gordo) and run the command as that user inside the docker images. Soon there will be policy in aurora enforcing this. 
[First hit on google about the subject.](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b)

**Comment by milesgranger** [comment]
Closed by #756
