### ISSUE TITLE
Argo: Retries broken

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#688]
In argo 2.4.2 the retry mechanism is fundamentally broken, and the retry steps are passed the [wrong parameters](https://github.com/argoproj/argo/issues/1719). So the second retry is just a completely different model... 
So, we can either disable retries, or downgrade to argo 2.3 everywhere.  2.3 means no pod GC, so then we need to clean up the pods in another way.

**Comment by flikka** [comment]
At some point, we'll test newer, hopefully working Argo version. Currently, we use 2.3
