### ISSUE TITLE
Add tag matching and asset to path for 1140, 1170, 1219

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#700]
1904 Johan Sverdrup
1140 Sleipner
1170 Heidrun
1219 Aasta Hansteen

**Comment by EinarJohnsen** [comment]
Are we able to infer the tag matching before the paths are created?

**Comment by flikka** [comment]
> Are we able to infer the tag matching before the paths are created?

I would guess that we could do the tag-to-asset, but not the asset-to-path.

Seems like "1904" is the prefix for 1904, 1140 sleipner has no prefix, 1170 Heidrun has "HD", and 1219 aasta has "1219".

**Comment by EinarJohnsen** [comment]
Took a look for these beauties, but sadly I can not see them yet.

**Comment by flikka** [comment]
@ryanjdillon this is related to https://github.com/equinor/gordo-infrastructure/issues/508  - closing this one
