### ISSUE TITLE
RFC: Ignore name/metadata in cache-key

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#703]
Should we explicitly ignore e.g. the name and the user-provided metadata when calculating the cache-key, and then rather populate these field with whatever we are provided? That will make the cache-key more tied to just the serialized model, and give more cache-hits.

**Comment by EinarJohnsen** [comment]
I think this is a good idéa. Unless there are things that I have not thought about that can be specified in the user-defined metadata which directly affects the model.

**Comment by ryanjdillon** [comment]
> I think this is a good idéa. Unless there are things that I have not thought about that can be specified in the user-defined metadata which directly affects the model.

The user defined metadata just gets passed through to the metadata, so neither affect the model. 

Orthoganal-but-similar... could keeping a table of aliases or something? Currently, logging of the metadata occurs when it is created AND pulled from the cache, which is helpful for the user (`my-forgotten-model` and `that-models-twin` both have metrics to quey), but in turn generates redunda-cruft.
