### ISSUE TITLE
Add more metadata about the actual dataset

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#779]
We have a metadata for dataset (eg. time taken to fetch data), another interesting thing:
* What was the _actual_ start and end timestamp (based on presence of data)?
* For each tag, how many datapoints were there, originally?

**Comment by ryanjdillon** [comment]
Though not in the `dataset` portion of the metadata, the CV split metadata that is now logged via #785 has this info, where the last fold is the entire dataset.

**Comment by milesgranger** [comment]
#776  restructures the metadata a bit so this should rather be in `metadata->build-metadata->dataset` so any dataset specific building metadata goes in there.

**Comment by ryanjdillon** [comment]
#785 is merged now with the CV folds start/end timestamps added to `metadata.build-metadata.model.cross-validation.splits`, should we duplicate this in the dataset metadata? 

I suppose if the dataset was refactored out, it could be beneficial to have this in its metadata ; though, I think this info is pretty readily attainable for anyone using the dataset.
