### ISSUE TITLE
Sort out dependabot errors with pip-comile

### ISSUE THREAD

**Issue by ryanjdillon** [equinor/gordo#786]
Currently dependabot is removing any subdependency of packages in `requirements.in` that are not is own. I.e. only packages explicitly listed and subpackages of the package being bumped are included in the `requirements.txt` generated by `dependabot`.

Currently things are setup with their UI, but we could setup a config file ([docs here](https://dependabot.com/docs/config-file/#dependabot-config-files)).

In case we need to dig further, it looks like pip-compile is called [here](https://github.com/dependabot/dependabot-core/blob/509bafdbafe90a734d65ceccd6c01b76383f63b1/python/lib/dependabot/python/file_updater/pip_compile_file_updater.rb#L65-L91) in `dependabot-core`.

**Comment by ryanjdillon** [comment]
It seem like [this](https://github.com/dependabot/dependabot-core/blob/master/python/helpers/lib/parser.py#L53) may be where we could alter what gets changed in the `.txt` req file.
```python
                pattern = r"-[cr] (.*) \(line \d+\)"
                abs_path = re.search(pattern, install_req.comes_from).group(1)
                rel_path = os.path.relpath(abs_path, directory)

                requirement_packages.append({
                    "name": install_req.req.name,
                    "version": version_from_install_req(install_req),
                    "markers": str(install_req.markers) or None,
                    "file": rel_path,
                    "requirement": str(install_req.specifier) or None,
                    "extras": sorted(list(install_req.extras))
})
```
Using the `.dependabot/config.yml`, we could point to our own parser where this is altered.

**Comment by milesgranger** [comment]
Seems maybe this is solved with the renaming/re-adding of the repo to dependabot.. last few PRs have been ok. :crossed_fingers:
