### ISSUE TITLE
Optimize influx schema for quering

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#878]
The influx schema consists of several measurements, e.g. model-input, model-output, resampled. The model-input/output schema has one `field` per tag, and then the machine name as a `tag`. This has the consequence that when querying for the output for a given machine you get a big matrix back with data for every possible sensor, not only the sensors used by that machine. This matrix has mostly `none` values (for all the sensors which are not part of the particular machine), but still becomes quite huge when running on projects with many sensors, and causes grafana to be quite slow and memory-hungry. 

Some alternatives: 
1. Add the sensor as a tag in addition to the machine, and change the field to e.g. `value`. 
1. Somehow encode somewhere in influx which sensors belong to a machine. Then the `Sensor` variable in grafana can be refactored to only contain these sensors, and then the query will be `select mean($Sensors)`, which maybe (maybe not) makes influx return a more narrow matrix?
1. Other?

Should we also ditch `resampled`? It made sense before we sendt up `model-input`. For the pure auto-encoder case it would be more effecient to ditch `model-input`, but for the general X-Y case there is no other way (that I can see) to know what the input-sensors are (short of fetching them from postgress, which we could).

**Comment by ryanjdillon** [comment]
@epa095 It appears the `write_points()` `batch_size` is hard-coded [here](https://github.com/ryanjdillon/gordo/blob/a39cf123868156394c0f3a75525874fc65e23b66/gordo/client/forwarders.py#L186-L188). You think this also might be slowing things down if the resources are limited?

```python
                self.dataframe_client.write_points(
                    dataframe=df, measurement=measurement, tags=tags, batch_size=10000
                )
```

**Comment by milesgranger** [comment]
But just to point out, that has nothing to do with _query_ performance.

**Comment by ryanjdillon** [comment]
Right, of coarse. I'll just let that sleeping dog lie.
