### ISSUE TITLE
Server: Provide `server-version` endpoint

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#885]

**Comment by milesgranger** [comment]
Seems we have that in the `/metadata` endpoint, is that enough?

https://github.com/equinor/gordo/blob/e170e312ff16fe6ec332d7d55f8b7c5674fac3d0/gordo/server/views/base.py#L212

**Comment by epa095** [comment]
Almost, but that requires one to have an actual model to ask about, and fish the resoult out of that. The use of this was to have a simple way for Lennart to print out the server version at the start, to see if there might be incompatabilities between it and the client.
